--
--Hibernate:
--    alter table if exists employee
--       drop constraint if exists UKqrbsk9ljmhfje93me0n7xwdxq
--2025-01-14T16:43:48.702-05:00  WARN 70770 --- [spring-boot-app] [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Warning Code: 0, SQLState: 00000
--2025-01-14T16:43:48.703-05:00  WARN 70770 --- [spring-boot-app] [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : constraint "ukqrbsk9ljmhfje93me0n7xwdxq" of relation "employee" does not exist, skipping
--Hibernate:
--    alter table if exists employee
--       add constraint UKqrbsk9ljmhfje93me0n7xwdxq unique (address_id)
--Hibernate:
--    alter table if exists employee
--       add constraint FKga73hdtpb67twlr9c1i337tyt
--       foreign key (address_id)
--       references address
--Hibernate:
--    alter table if exists employee
--       add constraint FKbejtwvg9bxus2mffsm3swj3u9
--       foreign key (department_id)
--       references department
--Hibernate:
--    alter table if exists employee_workgroup
--       add constraint FKvo009ue266vs58sybb7tafqx
--       foreign key (employee_id)
--       references employee
--Hibernate:
--    alter table if exists employee_workgroup
--       add constraint FK35mmrvbh27o4qmd4swkt1uxms
--       foreign key (workgroup_id)
--       references work_group